# Generated by Django 5.2 on 2025-04-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visits',
            new_name='VisitsLog',
        ),
    ]
